### ISSUE TITLE
Error opening the solution

### ISSUE THREAD

**Issue by hudhafah** [Qordobacode/api-sdk-c#4]
Unable to find version '1.0.0.2' of package 'Unirest-Qordoba'.

That's the error I got when opening the solution. Is 'Unirest-Qordoba' missing somehow?

Below shows the errors building the solution:

<img width="1067" alt="screen shot 2016-03-28 at 3 48 38 pm" src="https://cloud.githubusercontent.com/assets/18110729/14073559/a3ab3368-f4fc-11e5-9f49-5a13f43f6cd8.png">

**Comment by wassemgtk** [comment]
Hi @hudhafah  it’s not going to work without keys and latest version . Happy to give you test keys on the phone or GotToMeeting call. Email me a number and happy to call you.

**Comment by hudhafah** [comment]
My teammate has found alternative with functional SDK so we won't proceed with this. Thanks for the follow up though.
